export const characterOne=require("../assets/characters/char1.png")
export const characterTwo=require("../assets/characters/char2.png")
export const characterThree=require("../assets/characters/char3.png")
export const characterFour=require("../assets/characters/char4.png")
export const characterFive=require("../assets/characters/animeCh1.png")
export const characterSix=require("../assets/characters/spaceSh1.png")